/* Fully worked explanations, in the lecture's # notation. */
const VectorProofs = (() => {
  'use strict';
  const m = text => `<span class="math">${text}</span>`;
  const calc = rows => `<div class="calculation">${rows.map(([formula,reason]) => `<div class="calculation-line"><span class="math">${formula}</span><span class="calculation-reason">${reason}</span></div>`).join('')}</div>`;
  const proof = (intro,steps,result) => `<p class="proof-intro">${intro}</p><ol class="proof-steps">${steps.map(step=>`<li>${step}</li>`).join('')}</ol><p class="proof-result">${result}</p>`;
  const all = 'Como os elementos foram escolhidos arbitrariamente, a igualdade vale para todos os elementos exigidos pelo axioma.';
  const fail = 'Os dois resultados são diferentes. Um só caso permitido em que a igualdade falha basta para refutar o axioma.';
  const real = 'ℝ';

  function indexed(config) {
    const {setup,at,u,v,w,zero,zeroMember,inverse,inverseMember,finish} = config;
    const intro = `Usamos as operações definidas no enunciado. ${setup}`;
    const end = `O índice ou ponto escolhido era arbitrário. ${finish} Portanto a propriedade é satisfeita.`;
    return [
      proof('Queremos comparar (u # v) # w e u # (v # w).', [intro, calc([
        [`${at('(u # v) # w')} = ${at('u # v')} + ${w}`,'Definição da soma exterior.'],
        [`= (${u} + ${v}) + ${w}`,'Definição da soma u # v.'],
        [`= ${u} + (${v} + ${w})`,'Associatividade da adição de números reais.'],
        [`= ${u} + ${at('v # w')}`,'Definição de v # w, lida no sentido inverso.'],
        [`= ${at('u # (v # w)')}`,'Definição da soma exterior, lida no sentido inverso.']
      ]),finish],end),
      proof('Precisamos de um único candidato que funcione para qualquer u, à direita e à esquerda.',[
        `Escolhemos ${m(`0<sub>E</sub> = ${zero}`)}. ${zeroMember}`,
        intro + ' A componente ou o valor correspondente de 0<sub>E</sub> é 0.',
        'Somando o candidato à direita:'+calc([[`${at('u # 0<sub>E</sub>')} = ${u} + 0`,'Definição da soma.'],[`= ${u}`,'O número 0 é neutro para a adição real.']]),
        'Somando o mesmo candidato à esquerda:'+calc([[`${at('0<sub>E</sub> # u')} = 0 + ${u}`,'Definição da soma.'],[`= ${u}`,'O número 0 também é neutro à esquerda.']]),
        finish+' As duas somas são, por isso, iguais a u.'
      ],`O elemento ${m(zero)} pertence a E e é neutro dos dois lados, para qualquer u. A2 é satisfeita.`),
      proof('Fixamos um u qualquer de E e procuramos u′ em E cuja soma com u seja o neutro.',[
        `O neutro é ${m(zero)}. Escolhemos ${m(`u′ = ${inverse}`)}. ${inverseMember}`,
        intro + ` A componente ou valor de u′ é ${m(`−(${u})`)}.`,
        'Na primeira ordem:'+calc([[`${at('u # u′')} = ${u} + (−(${u}))`,'Substituímos u′ pela expressão escolhida.'],['= 0','Um número real somado ao seu oposto dá 0.'],[`= ${at('0<sub>E</sub>')}`,'É a componente ou valor do neutro.']]),
        'Na ordem inversa:'+calc([[`${at('u′ # u')} = −(${u}) + ${u}`,'Definição da soma e do candidato.'],['= 0','A soma destes dois números também é 0.'],[`= ${at('0<sub>E</sub>')}`,'Identificamos o neutro.']]),
        finish+' Logo u # u′ = u′ # u = 0<sub>E</sub>.'
      ],'A construção funciona para qualquer u de E. Assim, todos os vetores têm um simétrico em E.'),
      proof('Fixamos dois elementos u e v de E e comparamos as duas ordens da soma.',[intro,calc([
        [`${at('u # v')} = ${u} + ${v}`,'Definição de #.'],
        [`= ${v} + ${u}`,'Comutatividade da adição dos números reais.'],
        [`= ${at('v # u')}`,'Definição de # na ordem inversa.']
      ]),finish],end),
      proof('Fixamos u e v em E e um escalar real α qualquer.',[intro,calc([
        [`${at('α ⊙ (u # v)')} = α${at('u # v')}`,'Definição da multiplicação por α.'],
        [`= α(${u} + ${v})`,'Definição de u # v.'],
        [`= α${u} + α${v}`,'Distributividade da multiplicação de números reais.'],
        [`= ${at('α ⊙ u')} + ${at('α ⊙ v')}`,'Reconhecemos as duas multiplicações por α.'],
        [`= ${at('(α ⊙ u) # (α ⊙ v)')}`,'Definição da soma dos dois resultados.']
      ]),finish],end),
      proof('Fixamos u em E e dois escalares reais α e β quaisquer.',[intro,calc([
        [`${at('(α + β) ⊙ u')} = (α + β)${u}`,'Aplicamos a operação escalar ao escalar α + β.'],
        [`= α${u} + β${u}`,'Distributividade da multiplicação real.'],
        [`= ${at('α ⊙ u')} + ${at('β ⊙ u')}`,'Definição dos dois produtos por escalares.'],
        [`= ${at('(α ⊙ u) # (β ⊙ u)')}`,'Definição da soma #.']
      ]),finish],end),
      proof('Fixamos u em E e escalares reais α e β. Começamos pelo lado com duas operações sucessivas.',[intro,calc([
        [`${at('α ⊙ (β ⊙ u)')} = α${at('β ⊙ u')}`,'Aplicamos primeiro a definição da operação exterior.'],
        [`= α(β${u})`,'Aplicamos a definição da operação interior.'],
        [`= (αβ)${u}`,'Associatividade da multiplicação dos reais.'],
        [`= ${at('(αβ) ⊙ u')}`,'Definição da multiplicação pelo escalar αβ.']
      ]),finish],end),
      proof('Fixamos u em E. O escalar a usar é o número real 1.',[intro,calc([
        [`${at('1 ⊙ u')} = 1${u}`,'Definição da operação escalar.'],
        [`= ${u}`,'O número 1 é a identidade da multiplicação real.']
      ]),finish+' Concluímos que 1 ⊙ u = u.'],end)
    ];
  }
  const configs = {
    r2:{setup:'Escrevemos u = (u₁, u₂), v = (v₁, v₂) e w = (w₁, w₂). Escolhemos um índice i ∈ {1, 2}. A notação (a)ᵢ significa a i-ésima coordenada do par a.',at:a=>`(${a})<sub>i</sub>`,u:'uᵢ',v:'vᵢ',w:'wᵢ',zero:'(0, 0)',zeroMember:'As duas coordenadas são reais, logo (0, 0) ∈ ℝ².',inverse:'(−u₁, −u₂)',inverseMember:'Os opostos dos dois números reais u₁ e u₂ são reais, logo este par está em ℝ².',finish:'A igualdade vale para i = 1 e para i = 2. Dois pares com a mesma primeira coordenada e a mesma segunda coordenada são iguais.'},
    matrices:{setup:'Chamamos u, v e w às matrizes. Fixamos uma linha i ∈ {1, 2} e uma coluna j ∈ {1, 2}; uᵢⱼ é a entrada nessa posição. As regras do enunciado somam e multiplicam cada entrada separadamente.',at:a=>`(${a})<sub>ij</sub>`,u:'uᵢⱼ',v:'vᵢⱼ',w:'wᵢⱼ',zero:'a matriz cujas quatro entradas são 0',zeroMember:'Tem duas linhas, duas colunas e entradas reais, por isso pertence a M₂,₂(ℝ).',inverse:'a matriz de entradas −uᵢⱼ',inverseMember:'Negar cada entrada mantém as quatro entradas reais e não muda o tamanho da matriz.',finish:'Isto vale nas quatro posições (1,1), (1,2), (2,1) e (2,2). Matrizes do mesmo tamanho com todas as entradas iguais são a mesma matriz.'},
    polynomials:{setup:'Escrevemos u(x) = u₀ + u₁x + u₂x², e de modo análogo v e w. Fixamos k ∈ {0, 1, 2}. A notação coefₖ(p) designa o coeficiente de xᵏ em p. Na soma, o novo coeficiente é uₖ + vₖ; no produto por α, é αuₖ.',at:a=>`coef<sub>k</sub>(${a})`,u:'uₖ',v:'vₖ',w:'wₖ',zero:'o polinómio 0 + 0x + 0x²',zeroMember:'É da forma permitida, com os três coeficientes iguais a 0. O enunciado inclui o polinómio nulo.',inverse:'−u₀ − u₁x − u₂x²',inverseMember:'Os três coeficientes são reais e não aparece nenhum termo de grau superior a 2.',finish:'Obtivemos igualdade dos coeficientes para k = 0, 1 e 2. As expressões u₀ + u₁x + u₂x² com os mesmos três coeficientes são o mesmo polinómio.'},
    functions:{setup:'u, v e w são funções de ℝ em ℝ. Escolhemos um real t arbitrário. Por definição, (u # v)(t) = u(t) + v(t) e (α ⊙ u)(t) = αu(t). Os valores u(t), v(t) e w(t) são números reais.',at:a=>`(${a})(t)`,u:'u(t)',v:'v(t)',w:'w(t)',zero:'a função nula, que vale 0 em todo o t',zeroMember:'Atribui a cada real t o número real 0, logo é uma função de ℝ em ℝ.',inverse:'a função definida por u′(t) = −u(t)',inverseMember:'Como u(t) é real, −u(t) é real. Isto define uma função de ℝ em ℝ para todos os t.',finish:'O real t era arbitrário, portanto as duas funções dão o mesmo valor em todos os pontos do domínio. Esta é precisamente a definição de igualdade de funções.'},
    sequences:{setup:'Escrevemos u = (uₙ), v = (vₙ) e w = (wₙ). Fixamos um índice natural n ≥ 1 qualquer. O n-ésimo termo da soma é uₙ + vₙ, e o n-ésimo termo do produto por α é αuₙ.',at:a=>`(${a})<sub>n</sub>`,u:'uₙ',v:'vₙ',w:'wₙ',zero:'(0, 0, 0, …)',zeroMember:'É uma sucessão de números reais, com um termo para cada n ≥ 1.',inverse:'a sucessão (−uₙ)',inverseMember:'Para cada n, −uₙ é real, pelo que todos os termos da nova sucessão são permitidos.',finish:'Não escolhemos um valor especial de n: o cálculo vale para todo o n ≥ 1. Assim, as sucessões têm os mesmos termos em todos os índices e são iguais. Não estamos a somar uma série infinita.'},
    'complex-real':{setup:'Escrevemos cada complexo u = u₁ + iu₂, com u₁, u₂ reais, e o mesmo para v e w. A coordenada 1 é a parte real e a coordenada 2 é a parte imaginária. Como α é real, α(u₁ + iu₂) = αu₁ + iαu₂. Assim, as operações nas duas coordenadas são as operações reais habituais. Fixamos i ∈ {1, 2} como índice de coordenada (neste índice, a letra i não designa a unidade imaginária).',at:a=>`coord<sub>i</sub>(${a})`,u:'uᵢ',v:'vᵢ',w:'wᵢ',zero:'0 + 0i',zeroMember:'É um número complexo, portanto pertence a E = ℂ.',inverse:'−u₁ − iu₂',inverseMember:'As duas partes são reais, logo a expressão define um complexo.',finish:'A igualdade vale para as duas coordenadas reais. Dois complexos com a mesma parte real e a mesma parte imaginária são iguais.'},
    waves:{setup:'Escrevemos u(t) = u₁ sen t + u₂ cos t, e analogamente v e w. Estes coeficientes são únicos: em t = 0 o valor da função é u₂, e em t = π/2 é u₁. Somar funções soma os dois coeficientes; multiplicar por α multiplica os dois coeficientes por α, usando a distributividade real. Fixamos i ∈ {1, 2} para indicar um desses coeficientes.',at:a=>`coef<sub>i</sub>(${a})`,u:'uᵢ',v:'vᵢ',w:'wᵢ',zero:'a função 0 sen t + 0 cos t',zeroMember:'É da forma pedida com os dois coeficientes reais iguais a zero, e vale 0 em todos os pontos.',inverse:'a função −u₁ sen t − u₂ cos t',inverseMember:'Os dois novos coeficientes são reais; a função continua a ser uma combinação de seno e cosseno.',finish:'Os coeficientes do seno e do cosseno são iguais dos dois lados. Substituindo-os na expressão da função, obtemos o mesmo valor para todos os t, logo a mesma função.'},
    'plane-equation':{setup:'Escrevemos u = (u₁, u₂, u₃), v = (v₁, v₂, v₃) e w = (w₁, w₂, w₃), todos no plano. As operações são as usuais de ℝ³. Escolhemos uma coordenada i ∈ {1, 2, 3}.',at:a=>`(${a})<sub>i</sub>`,u:'uᵢ',v:'vᵢ',w:'wᵢ',zero:'(0, 0, 0)',zeroMember:'Substituindo na equação do plano, 0 − 0 + 0 = 0, logo o candidato pertence a E.',inverse:'(−u₁, −u₂, −u₃)',inverseMember:'Como u está no plano, u₁ − u₂ + u₃ = 0. Para o candidato, (−u₁) − (−u₂) + (−u₃) = −u₁ + u₂ − u₃ = −(u₁ − u₂ + u₃) = −0 = 0. Portanto também pertence a E.',finish:'A igualdade vale para i = 1, 2 e 3, portanto os três componentes coincidem e os vetores são iguais.'}
  };
  // Distinguish the coordinate index k from the imaginary unit i throughout.
  for (const key of ['setup','u','v','w']) configs['complex-real'][key]=configs['complex-real'][key].replace('Fixamos i ∈ {1, 2} como índice de coordenada (neste índice, a letra i não designa a unidade imaginária).','Fixamos um índice k ∈ {1, 2} para escolher uma das duas coordenadas reais.').replace(/uᵢ/g,'uₖ').replace(/vᵢ/g,'vₖ').replace(/wᵢ/g,'wₖ');
  configs['complex-real'].at=a=>`coord<sub>k</sub>(${a})`;

  function ordinary(field='ℝ') {
    const numbers=field==='ℝ'?'reais':'complexos';
    const start=`Escolhemos os elementos e escalares indicados em ${field}, sem lhes atribuir valores particulares. Nas contas abaixo, + e a multiplicação por justaposição são as operações usuais dos números ${numbers}; cada ocorrência de # ou ⊙ é substituída pela definição dada no enunciado.`;
    return [
      proof('Verificamos a associatividade da adição.',[start,calc([['(u # v) # w = (u + v) # w','Definição da soma interior.'],['= (u + v) + w','Definição da soma exterior.'],['= u + (v + w)',`Associatividade da adição dos ${numbers}.`],['= u # (v # w)','Aplicamos as definições, no sentido inverso.']]),'Nenhum passo depende de valores especiais de u, v ou w.'],all),
      proof('Procuramos um neutro que pertença ao conjunto.',[`O número 0 pertence a ${field}. Propomos 0<sub>E</sub> = 0.`,`Para um u qualquer, ${m('u # 0 = u + 0 = u')}, pela definição de # e pela propriedade do zero na adição usual.`,`Na outra ordem, ${m('0 # u = 0 + u = u')}, pelas mesmas duas razões.`],'O mesmo 0 funciona dos dois lados para todos os u. Logo é um elemento neutro.'),
      proof('Fixamos um u qualquer e procuramos o seu simétrico.',[`O neutro é 0. O candidato ${m('u′ = −u')} pertence a ${field}, porque o oposto de um número ${numbers==='reais'?'real':'complexo'} pertence ao mesmo corpo.`,calc([['u # u′ = u + (−u)','Definição de # e substituição do candidato.'],['= 0','Propriedade do oposto na adição usual.']]),calc([['u′ # u = (−u) + u','Calculamos também a outra ordem.'],['= 0','Os dois números são opostos.']])],'Para cada u encontrámos u′ no conjunto e ambas as somas dão o neutro.'),
      proof('Comparamos as duas ordens para u e v quaisquer.',[start,calc([['u # v = u + v','Definição de #.'],['= v + u',`Comutatividade da adição dos ${numbers}.`],['= v # u','Definição de #, no sentido inverso.']]),'A ordem dos dois elementos não altera o resultado.'],all),
      proof('Fixamos um escalar α e dois elementos u, v quaisquer.',[start,calc([['α ⊙ (u # v) = α(u + v)','Substituímos as duas operações pelas definições.'],['= αu + αv',`Distributividade nos ${numbers}.`],['= (α ⊙ u) # (α ⊙ v)','Voltamos à notação das operações dadas.']]),'Obtivemos exatamente o outro lado do axioma.'],all),
      proof('Fixamos escalares α, β e um elemento u quaisquer.',[start,calc([['(α + β) ⊙ u = (α + β)u','Definição da operação escalar.'],['= αu + βu',`Distributividade nos ${numbers}.`],['= (α ⊙ u) # (β ⊙ u)','Definições dos dois produtos e da soma #.']]),'A igualdade inclui também escalares nulos ou negativos.'],all),
      proof('Comparamos multiplicar duas vezes e multiplicar pelo produto dos escalares.',[start,calc([['α ⊙ (β ⊙ u) = α ⊙ (βu)','Definição da operação interior.'],['= α(βu)','Definição da operação exterior.'],['= (αβ)u',`Associatividade da multiplicação dos ${numbers}.`],['= (αβ) ⊙ u','Definição do produto pelo escalar αβ.']]),'O primeiro e o último membros são os dois lados pretendidos.'],all),
      proof('O enunciado deve valer para qualquer elemento u.',[`Escolhemos um u qualquer de ${field}.`,calc([['1 ⊙ u = 1u','Definição da operação escalar com α = 1.'],['= u',`O número 1 é neutro para a multiplicação dos ${numbers}.`]]),'Não usámos nenhuma hipótese adicional sobre u.'],'Logo multiplicar pelo escalar 1 deixa todos os elementos inalterados.')
    ];
  }
  const R=ordinary();
  const C=ordinary('ℂ');
  const proofs={};
  Object.keys(configs).forEach(id=>proofs[id]=indexed(configs[id]));

  proofs.positive=[
    proof('A operação # é o produto usual de números positivos.', ['Escolhemos u, v, w > 0. Os produtos uv e vw são positivos, logo as somas interiores estão em E.',calc([['(u # v) # w = (uv) # w','Definição de # na soma interior.'],['= (uv)w','Definição de # na soma exterior.'],['= u(vw)','Associatividade da multiplicação real.'],['= u # (v # w)','Aplicamos duas vezes a definição de # no sentido inverso.']]),'Assim, mudar os parênteses não muda o resultado.'],all),
    proof('O neutro da operação # não tem de ser o número 0.', ['Precisamos de um positivo e tal que ue = u para todo o u > 0. Escolhemos e = 1, que é positivo e pertence a E.',calc([['u # 1 = u × 1 = u','Definição de # e identidade da multiplicação real.']]),calc([['1 # u = 1 × u = u','Calculamos também a ordem inversa.']])],'Logo 0<sub>E</sub> = 1. Não afirmamos que 0<sub>E</sub> seja o número real 0.'),
    proof('O neutro desta soma é 1. Procuramos um positivo cuja soma # com u dê 1.', ['Fixamos u > 0. Como u não é zero, 1/u existe; como u é positivo, 1/u > 0. Portanto u′ = 1/u pertence a E.',calc([['u # u′ = u(1/u) = 1','Definição de # e propriedade do recíproco.']]),calc([['u′ # u = (1/u)u = 1','A mesma verificação pela esquerda.']]),'Ambos os resultados são o neutro 0<sub>E</sub> = 1.'],'Todo o u tem simétrico para #, e esse simétrico é 1/u, não o número −u.'),
    proof('Fixamos dois números positivos u e v.', ['Substituímos a operação abstrata pela sua definição: u # v = uv.',calc([['u # v = uv','Definição da soma.'],['= vu','Comutatividade da multiplicação real.'],['= v # u','Definição da soma na outra ordem.']]),'A igualdade vale para quaisquer positivos u e v.'],'A adição # é comutativa.'),
    proof('Fixamos u, v > 0 e α ∈ ℝ. Comparamos os dois lados usando a definição de potência real.', ['Para qualquer t > 0, usamos tᵅ = exp(α ln t). Como uv > 0, esta definição pode ser usada para t = uv.',calc([['α ⊙ (u # v) = (uv)ᵅ','Definições de # e ⊙.'],['= exp(α ln(uv))','Definição de potência de base positiva.'],['= exp(α(ln u + ln v))','Lei ln(uv) = ln u + ln v.'],['= exp(α ln u + α ln v)','Distributividade da multiplicação real.'],['= exp(α ln u) exp(α ln v)','Lei exp(s + t) = exp(s)exp(t).'],['= uᵅvᵅ','Definição das duas potências.'],['= (α ⊙ u) # (α ⊙ v)','A operação # é o produto usual.']]),'O cálculo também vale para α = 0 e α < 0, pois as bases são positivas.'],all),
    proof('Fixamos u > 0 e α, β ∈ ℝ.', ['A soma α + β é a soma usual de números. A soma # do lado direito é um produto.',calc([['(α + β) ⊙ u = u<sup>α+β</sup>','Definição de ⊙.'],['= exp((α + β) ln u)','Definição da potência real.'],['= exp(α ln u + β ln u)','Distributividade real.'],['= exp(α ln u) exp(β ln u)','Lei da exponencial de uma soma.'],['= uᵅuᵝ','Definição de cada potência.'],['= (α ⊙ u) # (β ⊙ u)','Definições de # e ⊙.']]),'O primeiro e o último membros são os dois lados de A6.'],all),
    proof('Fixamos u > 0 e α, β ∈ ℝ. O número uᵝ é positivo, pelo que podemos aplicar-lhe a operação outra vez.', ['Pela definição de potência, uᵝ = exp(β ln u), logo ln(uᵝ) = β ln u.',calc([['α ⊙ (β ⊙ u) = (uᵝ)ᵅ','Aplicamos as duas definições de ⊙.'],['= exp(α ln(uᵝ))','Definição da potência exterior.'],['= exp(α(β ln u))','Usamos a identidade da primeira etapa.'],['= exp((αβ) ln u)','Associatividade da multiplicação real.'],['= u<sup>αβ</sup>','Definição de potência.'],['= (αβ) ⊙ u','Definição do produto pelo escalar αβ.']]),'A ordem das duas aplicações dá o mesmo que usar o produto dos escalares.'],all),
    proof('O escalar é 1 e o vetor u é qualquer positivo.', ['Aplicamos exatamente a regra α ⊙ u = uᵅ com α = 1.',calc([['1 ⊙ u = u¹','Definição da operação.'],['= exp(1 × ln u)','Definição da potência.'],['= exp(ln u) = u','1 × ln u = ln u e exp é inversa de ln nos positivos.']]),'O resultado é o próprio u.'],'A identidade escalar é satisfeita para todos os positivos.')
  ];

  function translated(k,transport) {
    // # is u + v − k. With transport, α⊙u = k + α(u−k); otherwise αu.
    const K=k<0?`(${k})`:String(k), twice=2*k;
    const S=`u # v = u + v − ${K}`;
    const base=[
      proof('Escolhemos três reais u, v e w. Vamos calcular separadamente os dois lados.',[`${S}.`,calc([[`(u # v) # w = (u + v − ${K}) # w`,'Definição da soma interior.'],[`= (u + v − ${K}) + w − ${K}`,'Definição da soma exterior.'],[`= u + v + w − (${twice})`,'Reagrupamos somas reais e juntamos os dois termos constantes.']]),calc([[`u # (v # w) = u # (v + w − ${K})`,'Definição da soma interior.'],[`= u + (v + w − ${K}) − ${K}`,'Definição da soma exterior.'],[`= u + v + w − (${twice})`,'Associatividade da soma real e simplificação dos termos constantes.']])],'Os dois lados dão a mesma expressão para quaisquer u, v, w. A1 é satisfeita.'),
      proof('Para encontrar o neutro, procuramos e tal que u # e = u para qualquer u.',[`${m(`u # e = u + e − ${K}`)}. Para obter u, escolhemos ${m(`e = ${k}`)}. Este número é real, logo pertence a E.`,calc([[`u # ${K} = u + ${K} − ${K} = u`,'Substituímos o candidato na soma pela direita.']]),calc([[`${K} # u = ${K} + u − ${K} = u`,'Pela esquerda, reagrupamos a adição usual e simplificamos.']])],`Logo o neutro de # é ${m(String(k))}.`),
      proof('O simétrico deve produzir o neutro da operação, não necessariamente o número 0.',[`O neutro é ${k}. A equação u # u′ = ${k} significa u + u′ − (${k}) = ${k}; somando (${k}) e subtraindo u na aritmética real, obtemos u′ = ${twice} − u. Este é um número real.`,calc([[`u # (${twice} − u) = u + (${twice} − u) − (${k})`,'Definição de #.'],[`= (u − u) + ${twice} − (${k}) = ${k}`,'Reagrupamos e simplificamos.']]),calc([[`(${twice} − u) # u = (${twice} − u) + u − (${k})`,'Calculamos na ordem inversa.'],[`= ${twice} + (−u + u) − (${k}) = ${k}`,'Reagrupamos e simplificamos.']])],`O candidato está em E e ambas as somas dão ${k}. Portanto é um simétrico.`),
      proof('Fixamos reais u e v arbitrários.',[S,calc([[`u # v = u + v − ${K}`,'Definição de #.'],[`= v + u − ${K}`,'Comutatividade da adição usual dos reais.'],['= v # u','Definição da soma na outra ordem.']]),'A constante acrescentada ou subtraída é a mesma nas duas ordens.'],all)
    ];
    if(!transport) return base.concat([
      proof('Para refutar A5 basta um escalar e dois vetores permitidos com resultados diferentes.', ['Escolhemos α = 0, u = 0 e v = 0. Todos são reais, pelo que são permitidos.',calc([['u # v = 0 + 0 + 1 = 1','Calculamos primeiro a soma interior.'],['α ⊙ (u # v) = 0 ⊙ 1 = 0 × 1 = 0','A multiplicação escalar é a usual.']]),calc([['α ⊙ u = 0 × 0 = 0; α ⊙ v = 0 × 0 = 0','Calculamos separadamente os dois produtos.'],['(α ⊙ u) # (α ⊙ v) = 0 # 0','Substituímos os resultados.'],['= 0 + 0 + 1 = 1','Aqui é obrigatório usar a soma modificada.']])],fail+' Neste caso, 0 ≠ 1.'),
      proof('Procuramos uma falha da distributividade sobre a soma de escalares.', ['Escolhemos α = β = 0 e u = 0; todos pertencem aos conjuntos exigidos.',calc([['(α + β) ⊙ u = (0 + 0) ⊙ 0','Substituímos os valores.'],['= 0 × 0 = 0','Somamos os escalares e usamos o produto usual.']]),calc([['α ⊙ u = 0; β ⊙ u = 0','Cada produto é 0 × 0.'],['(α ⊙ u) # (β ⊙ u) = 0 # 0','Substituímos os produtos.'],['= 0 + 0 + 1 = 1','Definição de #.']])],fail+' Assim, A6 falha.'),R[6],R[7]]);
    return base.concat([
      proof('Fixamos u, v, α ∈ ℝ e usamos as duas operações modificadas.', ['Primeiro calculamos o lado esquerdo:'+calc([['α ⊙ (u # v) = 3 + α((u + v − 3) − 3)','Definições de # e ⊙.'],['= 3 + α(u + v − 6)','Simplificamos dentro dos parênteses.'],['= 3 + αu + αv − 6α','Distribuímos α sobre os três termos.']]),'Agora o lado direito:'+calc([['(α ⊙ u) # (α ⊙ v) = [3 + α(u − 3)] # [3 + α(v − 3)]','Definição de cada produto escalar.'],['= [3 + α(u − 3)] + [3 + α(v − 3)] − 3','Definição da soma #.'],['= 3 + αu − 3α + 3 + αv − 3α − 3','Distribuímos os produtos.'],['= 3 + αu + αv − 6α','Agrupamos os termos iguais.']]),'Os resultados finais são iguais.'],all),
      proof('Fixamos α, β, u ∈ ℝ. A soma α + β é a soma usual dos escalares.', ['Lado esquerdo:'+calc([['(α + β) ⊙ u = 3 + (α + β)(u − 3)','Definição de ⊙.'],['= 3 + α(u − 3) + β(u − 3)','Distributividade real.']]),'Lado direito:'+calc([['(α ⊙ u) # (β ⊙ u) = [3 + α(u − 3)] # [3 + β(u − 3)]','Definição de cada produto.'],['= [3 + α(u − 3)] + [3 + β(u − 3)] − 3','Definição de #.'],['= 3 + α(u − 3) + β(u − 3)','Os termos constantes 3 + 3 − 3 dão 3.']]),'Obtivemos a mesma expressão.'],all),
      proof('Fixamos reais α, β e u. Calculamos primeiro o produto interior.', [calc([['β ⊙ u = 3 + β(u − 3)','Definição da operação com o escalar β.']]),calc([['α ⊙ (β ⊙ u) = 3 + α([3 + β(u − 3)] − 3)','Aplicamos a definição exterior ao resultado anterior.'],['= 3 + α(β(u − 3))','Dentro dos parênteses, 3 − 3 = 0.'],['= 3 + (αβ)(u − 3)','Associatividade da multiplicação real.'],['= (αβ) ⊙ u','É a definição do produto pelo escalar αβ.']]),'Não usámos restrições sobre α, β ou u.'],all),
      proof('Fixamos um real u qualquer e substituímos α por 1.',[calc([['1 ⊙ u = 3 + 1(u − 3)','Definição da operação.'],['= 3 + u − 3','Multiplicar um real por 1 não o altera.'],['= u','Os termos +3 e −3 anulam-se.']]),'O resultado é o próprio elemento escolhido.','A verificação serve para todos os reais u.'],'A8 é satisfeita.')
    ]);
  }
  proofs.shifted=translated(3,true);
  proofs.mismatch=translated(-1,false);

  function maximum(binary) {
    const domain=binary?'E = {0, 1}':'E = ℝ';
    return [
      proof('Fixamos u, v, w em E. A operação # escolhe o maior dos dois argumentos.', [`${domain}. Pelo menos um dos três números é maior ou igual aos outros dois. Consideramos todas as possibilidades; se houver empate, as contas continuam válidas.`,
        'Se u ≥ v e u ≥ w:'+calc([['(u # v) # w = máx(máx(u,v),w) = máx(u,w) = u','A primeira comparação escolhe u, e a segunda também.'],['u # (v # w) = máx(u,máx(v,w)) = u','v e w são ambos ≤ u, por isso o seu máximo também é ≤ u.']]),
        'Se v ≥ u e v ≥ w:'+calc([['(u # v) # w = máx(v,w) = v','O máximo de u e v é v.'],['u # (v # w) = máx(u,v) = v','O máximo de v e w é v.']]),
        'Se w ≥ u e w ≥ v:'+calc([['(u # v) # w = máx(máx(u,v),w) = w','O máximo de u e v é ≤ w.'],['u # (v # w) = máx(u,w) = w','O máximo de v e w é w.']])
      ],'Em todos os casos, as duas expressões são iguais. Estes casos cobrem quaisquer três elementos de E, logo A1 é satisfeita.'),
      binary?proof('Só há dois vetores. Vamos verificar o candidato 0 em todos os casos.', ['O número 0 pertence a E. Propomos 0<sub>E</sub> = 0.',calc([['0 # 0 = máx(0,0) = 0','Quando u = 0, somar o candidato dá u dos dois lados.'],['1 # 0 = máx(1,0) = 1','Quando u = 1, somar o candidato à direita dá u.'],['0 # 1 = máx(0,1) = 1','Quando u = 1, somar o candidato à esquerda também dá u.']]),'Não existem outros valores de u a verificar, pois E = {0,1}.'],'O elemento 0 é neutro dos dois lados para todos os vetores.'):proof('Um elemento neutro teria de ser um real e que funcionasse para todos os reais u.', ['Escolhemos um candidato e ∈ ℝ arbitrário. Não supomos que seja 0 nem um outro número particular.',`O número ${m('u = e − 1')} também é real, logo pertence a E. Além disso, e > e − 1.`,calc([['e # u = máx(e,e − 1) = e','O maior dos dois números é e.'],['u = e − 1 ≠ e','A diferença entre e e e − 1 é 1.']]),'Assim, este e não deixa u inalterado. Como podemos fazer a mesma escolha u = e − 1 para qualquer candidato e, nenhum real serve.'],'Não existe elemento neutro em E. O símbolo −∞ não resolve o problema, porque −∞ não é um número real e não pertence a E.'),
      binary?proof('O neutro é 0. Basta encontrar um vetor que não tenha simétrico.', ['Escolhemos u = 1, que pertence a E. Se existisse um simétrico u′, teria de ser um dos elementos 0 ou 1.',calc([['1 # 0 = máx(1,0) = 1 ≠ 0','O candidato u′ = 0 não funciona.'],['1 # 1 = máx(1,1) = 1 ≠ 0','O candidato u′ = 1 também não funciona.']]),'Esgotámos todos os candidatos em E. Em particular, nem sequer a soma numa das ordens pode dar o neutro.'],'O vetor 1 não tem simétrico; por isso A3 falha.'):proof('Na formulação da aula, o 0<sub>E</sub> de A3 é o elemento neutro exigido por A2.', ['Primeiro seria necessário um real e neutro para #. Para qualquer candidato e, o real e − 1 dá máx(e,e − 1) = e ≠ e − 1. Portanto não existe neutro.', 'Um simétrico de u teria de satisfazer u # u′ = u′ # u = 0<sub>E</sub>, com 0<sub>E</sub> igual a esse neutro.', 'Como esse neutro não existe nesta estrutura, não podemos fornecer simétricos relativamente a ele. Escolher um real arbitrário e chamar-lhe zero não satisfaz a definição da aula.'],'A3 não é satisfeita no sentido usado nas notas. A falta de A2 não pode ser apresentada aqui como uma falha isolada.'),
      proof('Fixamos u e v em E e comparamos as duas ordens.', ['Se u ≥ v, o maior número é u.',calc([['u # v = máx(u,v) = u','Ordem u, v.'],['v # u = máx(v,u) = u','A troca da ordem não muda qual é o maior número.']]),'Se u < v, o maior número é v:'+calc([['u # v = máx(u,v) = v','Ordem u, v.'],['v # u = máx(v,u) = v','Ordem v, u.']]),'As duas situações cobrem todos os casos, incluindo u = v no primeiro caso.'],'As duas somas são sempre iguais. A4 é satisfeita.'),
      proof('Fixamos α ∈ ℝ e u, v em E. Todos os escalares deixam cada vetor inalterado.', [calc([['α ⊙ (u # v) = u # v','A regra α ⊙ t = t aplica-se também a t = u # v.'],['= máx(u,v)','Definição de #.']]),calc([['α ⊙ u = u; α ⊙ v = v','Definição da ação dos escalares, aplicada separadamente.'],['(α ⊙ u) # (α ⊙ v) = u # v = máx(u,v)','Substituímos os dois resultados e calculamos #.']]),'Os dois lados deram o mesmo máximo.'],all),
      proof('Fixamos escalares reais α, β e um vetor u em E.', [calc([['(α + β) ⊙ u = u','A regra aplica-se a qualquer escalar, incluindo α + β = 0.']]),calc([['α ⊙ u = u; β ⊙ u = u','Cada escalar, separadamente, devolve u.'],['(α ⊙ u) # (β ⊙ u) = u # u','Substituímos esses resultados.'],['= máx(u,u) = u','O maior de dois números iguais a u é u.']]),'O resultado dos dois lados é u. Não usámos a regra dos espaços vetoriais 0 ⊙ u = 0<sub>E</sub>, que não faz parte da definição desta operação.'],all),
      proof('Fixamos α, β ∈ ℝ e u em E.', [calc([['(αβ) ⊙ u = u','A definição vale para o escalar αβ, seja qual for o produto.']]),calc([['β ⊙ u = u','Primeira aplicação da operação.'],['α ⊙ (β ⊙ u) = α ⊙ u = u','Substituímos o resultado e aplicamos novamente a regra.']]),'As duas expressões dão u.'],all),
      proof('Fixamos u em E e usamos o escalar 1.', ['A regra dada é α ⊙ u = u para todo o real α, sem exceções.',calc([['1 ⊙ u = u','Substituímos α por 1 na própria definição.']]),'O mesmo cálculo aplica-se a cada elemento do conjunto.'],'A8 é satisfeita.')
    ];
  }
  proofs.a2=maximum(false);proofs.a3=maximum(true);

  proofs.a1=[
    proof('Vamos usar três vetores permitidos e calcular as duas formas de pôr parênteses.',[
      'Escolhemos u = (1,0), v = (0,1) e w = (0,1). Todos pertencem a ℝ². Para somar quaisquer pares a = (a₁,a₂) e b = (b₁,b₂), comparamos a₁b₂ com a₂b₁. Se forem iguais, usamos a + b; se forem diferentes, usamos 2(a + b).',
      'Primeiro, o lado esquerdo:'+calc([['u₁v₂ = 1 × 1 = 1; u₂v₁ = 0 × 0 = 0','Os produtos são diferentes: 1 ≠ 0.'],['u # v = 2(u + v) = 2(1 + 0, 0 + 1) = (2,2)','Usamos a regra que duplica a soma.'],['2 × 1 = 2; 2 × 0 = 0','Para somar (2,2) a w = (0,1), comparamos de novo os dois produtos. São diferentes.'],['(u # v) # w = 2((2,2) + (0,1))','A soma exterior também exige a duplicação.'],['= 2(2 + 0, 2 + 1) = 2(2,3) = (4,6)','Somamos as coordenadas e multiplicamos ambas por 2.']]),
      'Agora, o lado direito:'+calc([['v₁w₂ = 0 × 1 = 0; v₂w₁ = 1 × 0 = 0','Estes dois produtos são iguais.'],['v # w = v + w = (0 + 0, 1 + 1) = (0,2)','Usamos a soma sem duplicação.'],['1 × 2 = 2; 0 × 0 = 0','Para somar u = (1,0) a (0,2), os produtos são diferentes.'],['u # (v # w) = 2((1,0) + (0,2))','Aplicamos a regra que duplica a soma exterior.'],['= 2(1 + 0, 0 + 2) = 2(1,2) = (2,4)','Calculamos cada coordenada.']]),
      'Os resultados são (4,6) e (2,4). Já as primeiras coordenadas, 4 e 2, são diferentes.'
    ],fail),
    proof('Propomos o vetor z = (0,0) para elemento neutro.', ['z pertence a ℝ². Fixamos u = (u₁,u₂) arbitrário.',calc([['u₁z₂ = u₁ × 0 = 0; u₂z₁ = u₂ × 0 = 0','Os produtos são iguais, logo usamos a soma sem duplicação.'],['u # z = u + z = (u₁ + 0, u₂ + 0) = (u₁,u₂) = u','O zero não altera nenhuma coordenada.']]),calc([['z₁u₂ = 0 × u₂ = 0; z₂u₁ = 0 × u₁ = 0','Na ordem inversa, os produtos também são iguais.'],['z # u = z + u = (0 + u₁, 0 + u₂) = u','A soma na outra ordem também devolve u.']])],'O mesmo z funciona para todo o u, dos dois lados. Portanto 0<sub>E</sub> = (0,0).'),
    proof('O neutro é (0,0). Fixamos u = (u₁,u₂) e propomos u′ = (−u₁,−u₂).', ['As duas coordenadas de u′ são reais, por isso u′ pertence a E.',calc([['u₁u′₂ = u₁(−u₂) = −u₁u₂','Primeiro produto a comparar.'],['u₂u′₁ = u₂(−u₁) = −u₂u₁ = −u₁u₂','Segundo produto: a multiplicação real é comutativa.'],['u # u′ = u + u′ = (u₁ − u₁, u₂ − u₂) = (0,0)','Os produtos são iguais, por isso não duplicamos a soma.']]),calc([['u′₁u₂ = (−u₁)u₂ = −u₁u₂','Primeiro produto na ordem inversa.'],['u′₂u₁ = (−u₂)u₁ = −u₂u₁ = −u₁u₂','O segundo produto tem o mesmo valor.'],['u′ # u = u′ + u = (−u₁ + u₁, −u₂ + u₂) = (0,0)','A soma sem duplicação também dá o neutro nesta ordem.']])],'Encontrámos um simétrico em E para qualquer u. A3 é satisfeita.'),
    proof('Fixamos quaisquer u e v em ℝ². Primeiro verificamos que trocar a ordem não muda o ramo escolhido.', [calc([['v₁u₂ = u₂v₁; v₂u₁ = u₁v₂','Pela comutatividade da multiplicação real, os produtos da ordem inversa são os produtos originais trocados.']]),'Logo u₁v₂ = u₂v₁ se, e somente se, v₁u₂ = v₂u₁. Além disso, a soma usual dos pares é comutativa:'+calc([['u + v = (u₁ + v₁, u₂ + v₂)','Definição da soma usual.'],['= (v₁ + u₁, v₂ + u₂) = v + u','Comutatividade da adição real em cada coordenada.']]),'Se u₁v₂ = u₂v₁, as duas ordens usam o primeiro ramo:'+calc([['u # v = u + v = v + u = v # u','Não há duplicação em nenhuma das ordens.']]),'Se u₁v₂ ≠ u₂v₁, as duas ordens usam o segundo ramo:'+calc([['u # v = 2(u + v) = 2(v + u) = v # u','A duplicação é a mesma nas duas ordens.']])],'Os produtos são iguais ou diferentes; verificámos ambos os casos. A4 é satisfeita.'),
    proof('Fixamos u, v ∈ ℝ² e α ∈ ℝ. É necessário verificar a escolha do ramo da soma.', [
      'Se α = 0, calculamos separadamente:'+calc([['0 ⊙ (u # v) = 0(u # v) = (0,0)','Multiplicar as duas coordenadas de qualquer par por 0 dá (0,0).'],['(0 ⊙ u) # (0 ⊙ v) = (0,0) # (0,0)','Cada produto escalar dá (0,0).'],['= (0,0) + (0,0) = (0,0)','Os produtos a comparar são 0 × 0 e 0 × 0, iguais; usamos o primeiro ramo.']]),
      'Suponhamos agora α ≠ 0. Para os pares αu e αv, os produtos a comparar são:'+calc([['(αu₁)(αv₂) = α²u₁v₂','Reordenamos os fatores reais.'],['(αu₂)(αv₁) = α²u₂v₁','Fazemos o mesmo no outro produto.']])+'Como α² ≠ 0, podemos dividir ambos os produtos por α². Assim, estes produtos são iguais exatamente quando u₁v₂ = u₂v₁. A soma original e a soma dos pares multiplicados usam o mesmo ramo.',
      'Se u₁v₂ = u₂v₁:'+calc([['α ⊙ (u # v) = α(u + v)','Primeiro ramo de # e definição de ⊙.'],['= (α(u₁ + v₁), α(u₂ + v₂))','Calculamos as duas coordenadas.'],['= (αu₁ + αv₁, αu₂ + αv₂) = αu + αv','Distributividade real em cada coordenada.'],['(α ⊙ u) # (α ⊙ v) = (αu) # (αv) = αu + αv','A soma dos pares multiplicados também usa o primeiro ramo.']]),
      'Se u₁v₂ ≠ u₂v₁:'+calc([['α ⊙ (u # v) = α[2(u + v)]','Segundo ramo de # e definição de ⊙.'],['= (2α(u₁ + v₁), 2α(u₂ + v₂))','Associatividade e comutatividade reais nas duas coordenadas.'],['= (2(αu₁ + αv₁), 2(αu₂ + αv₂))','Distributividade real.'],['= 2(αu + αv)','Voltamos à notação de pares.'],['(α ⊙ u) # (α ⊙ v) = 2(αu + αv)','Os pares multiplicados também usam o segundo ramo.']])
    ],'Verificámos α = 0 e α ≠ 0, e ambos os ramos possíveis da soma. A5 é satisfeita para todos os dados.'),
    proof('Fixamos α, β ∈ ℝ e u = (u₁,u₂). Primeiro comparamos os produtos para os pares αu e βu.',[calc([['(αu₁)(βu₂) = αβu₁u₂','Primeiro produto: reordenamos os fatores reais.'],['(αu₂)(βu₁) = αβu₂u₁ = αβu₁u₂','Segundo produto: a multiplicação real é comutativa.']])+'Os produtos são iguais, incluindo quando algum escalar é zero. A soma destes pares usa sempre o primeiro ramo.',calc([['(α ⊙ u) # (β ⊙ u) = (αu) # (βu)','Definição da operação escalar.'],['= αu + βu','Usamos o primeiro ramo, como acabámos de verificar.'],['= (αu₁ + βu₁, αu₂ + βu₂)','Soma usual dos pares.'],['= ((α + β)u₁, (α + β)u₂)','Distributividade real nas duas coordenadas.'],['= (α + β) ⊙ u','Definição da operação escalar.']]),'Isto vale para quaisquer α, β, u.'],'A6 é satisfeita.'),
    proofs.r2[6],proofs.r2[7]
  ];

  function scaledReal(square) {
    const factor=square?'α²':'|α|';
    return R.slice(0,4).concat([
      proof('A adição # é a soma usual. Fixamos α, u, v ∈ ℝ.',[`${m(factor)} é um número real fixo quando α está fixado.`,calc([[`α ⊙ (u # v) = ${factor}(u + v)`,'Definições das duas operações.'],[`= ${factor}u + ${factor}v`,'Distributividade da multiplicação real por este fator.'],['= (α ⊙ u) + (α ⊙ v)','Definição de cada produto escalar, no sentido inverso.'],['= (α ⊙ u) # (α ⊙ v)','A soma # é a adição usual.']]),'Não foi necessário supor α positivo.'],all),
      square?proof('Vamos testar α = 1, β = 1 e u = 1. Todos são reais.', [calc([['(α + β) ⊙ u = (1 + 1) ⊙ 1','Substituímos os dados.'],['= 2² × 1 = 4','Primeiro somamos os escalares; depois elevamos ao quadrado.']]),calc([['α ⊙ u = 1² × 1 = 1','Primeiro produto.'],['β ⊙ u = 1² × 1 = 1','Segundo produto.'],['(α ⊙ u) # (β ⊙ u) = 1 # 1 = 1 + 1 = 2','Só depois somamos os dois resultados.']]),'Como 4 ≠ 2, a identidade de A6 não vale para esta escolha permitida.'],fail):proof('Escolhemos α = 1, β = −1 e u = 1, todos reais.',[calc([['(α + β) ⊙ u = (1 − 1) ⊙ 1 = 0 ⊙ 1','Somamos primeiro os escalares.'],['= |0| × 1 = 0','Aplicamos a definição da operação.']]),calc([['α ⊙ u = |1| × 1 = 1','Primeiro produto.'],['β ⊙ u = |−1| × 1 = 1','O valor absoluto de −1 é 1.'],['(α ⊙ u) # (β ⊙ u) = 1 + 1 = 2','A soma # é a usual.']]),'O lado esquerdo deu 0 e o direito deu 2.'],fail),
      square?proof('Fixamos reais α, β e u e calculamos as operações sucessivas.', [calc([['β ⊙ u = β²u','Definição do produto interior.'],['α ⊙ (β ⊙ u) = α²(β²u)','Definição do produto exterior.'],['= (αα)(ββ)u = (αβ)(αβ)u','Associatividade e comutatividade da multiplicação dos números reais.'],['= (αβ)²u','Definição de quadrado.'],['= (αβ) ⊙ u','Definição da operação com o escalar αβ.']]),'O cálculo usa o produto dos escalares, não a soma.','A igualdade vale também se um deles for zero.'],all):proof('Fixamos reais α, β e u.', ['Para quaisquer reais a e b, |ab| = |a||b|: ambos os membros são não negativos e os seus quadrados são a²b²; dois reais não negativos com o mesmo quadrado são iguais.',calc([['α ⊙ (β ⊙ u) = |α|(|β|u)','Aplicamos a definição duas vezes.'],['= (|α||β|)u','Associatividade da multiplicação real.'],['= |αβ|u','Usamos a propriedade do valor absoluto da primeira etapa.'],['= (αβ) ⊙ u','Definição da operação com o escalar αβ.']]),'A propriedade do valor absoluto inclui escalares negativos e nulos.'],all),
      proof('Fixamos u ∈ ℝ e usamos o escalar 1.',[calc([[square?'1 ⊙ u = 1²u':'1 ⊙ u = |1|u','Definição da operação.'],['= 1u','Tanto 1² como |1| são iguais a 1.'],['= u','Identidade da multiplicação usual.']]),'O resultado é o próprio elemento u.','Não foi imposta nenhuma condição especial a u.'],'A8 é satisfeita.')
    ]);
  }
  proofs.a6=scaledReal(true);proofs.absolute=scaledReal(false);
  proofs.a8=R.slice(0,4).concat([
    proof('Fixamos α, u, v ∈ ℝ. Qualquer aplicação da operação escalar dá 0.',[calc([['α ⊙ (u # v) = α ⊙ (u + v) = 0','A regra ignora o valor do vetor u + v.']]),calc([['α ⊙ u = 0; α ⊙ v = 0','Aplicamos a regra a cada vetor.'],['(α ⊙ u) # (α ⊙ v) = 0 # 0 = 0 + 0 = 0','A soma # é a adição usual.']]),'Ambos os lados são 0 para quaisquer dados.'],'A5 é satisfeita.'),
    proof('Fixamos α, β, u ∈ ℝ.',[calc([['(α + β) ⊙ u = 0','A operação dá 0 seja qual for o escalar α + β.']]),calc([['α ⊙ u = 0; β ⊙ u = 0','Cada um dos dois produtos dá 0.'],['(α ⊙ u) # (β ⊙ u) = 0 # 0 = 0','Somamos pela operação usual.']]),'Obtivemos 0 dos dois lados.'],'A6 é satisfeita para todos os escalares e vetores.'),
    proof('Fixamos α, β, u ∈ ℝ e calculamos os dois lados.',[calc([['(αβ) ⊙ u = 0','A operação escalar dá 0 para qualquer produto αβ.']]),calc([['β ⊙ u = 0','Primeira aplicação da operação.'],['α ⊙ (β ⊙ u) = α ⊙ 0 = 0','O vetor 0 também é enviado para 0.']]),'Os dois resultados coincidem.'],'A7 é satisfeita.'),
    proof('Para refutar A8 basta um vetor que não seja conservado pelo escalar 1.', ['Escolhemos o vetor u = 1. Este vetor pertence a E = ℝ. O escalar 1 também pertence ao corpo ℝ.',calc([['1 ⊙ u = 1 ⊙ 1 = 0','A regra dá 0 para qualquer escalar, incluindo 1.'],['u = 1 ≠ 0','O resultado não é o vetor de partida.']]),'Logo a igualdade 1 ⊙ u = u não vale para este vetor permitido.'],'A8 falha.')
  ]);
  proofs.projection=proofs.r2.slice(0,4).concat([
    proof('Fixamos u = (x,y), v = (s,t) em ℝ² e α ∈ ℝ.', [calc([['u # v = (x + s, y + t)','Soma usual dos pares.'],['α ⊙ (u # v) = (α(x + s), 0)','A regra escalar multiplica a primeira coordenada e apaga a segunda.'],['= (αx + αs, 0)','Distributividade real na primeira coordenada.']]),calc([['α ⊙ u = (αx,0); α ⊙ v = (αs,0)','Calculamos cada produto separadamente.'],['(α ⊙ u) # (α ⊙ v) = (αx + αs, 0 + 0) = (αx + αs,0)','Somamos as duas coordenadas.']]),'As primeiras coordenadas são iguais, e ambas as segundas coordenadas são 0.'],all),
    proof('Fixamos u = (x,y) em ℝ² e reais α e β.', [calc([['(α + β) ⊙ u = ((α + β)x, 0)','Definição do produto escalar.'],['= (αx + βx, 0)','Distributividade real.']]),calc([['α ⊙ u = (αx,0); β ⊙ u = (βx,0)','Aplicamos a regra a cada escalar.'],['(α ⊙ u) # (β ⊙ u) = (αx + βx, 0 + 0) = (αx + βx,0)','Definição da soma usual dos pares.']]),'Os dois pares são iguais, coordenada a coordenada.'],all),
    proof('Fixamos u = (x,y) e escalares reais α e β.', [calc([['β ⊙ u = (βx,0)','Primeira multiplicação; a segunda coordenada torna-se 0.'],['α ⊙ (β ⊙ u) = α ⊙ (βx,0) = (α(βx),0)','Aplicamos a regra ao novo par.'],['= ((αβ)x,0)','Associatividade da multiplicação real.'],['= (αβ) ⊙ (x,y)','É precisamente a regra aplicada diretamente com αβ.']]),'Apagar a segunda coordenada duas vezes não provoca uma alteração adicional.','Nenhuma restrição foi imposta aos valores escolhidos.'],all),
    proof('Escolhemos o vetor u = (0,1), que pertence a ℝ².', [calc([['1 ⊙ (0,1) = (1 × 0,0)','Aplicamos a definição com α = 1.'],['= (0,0)','Simplificamos a primeira coordenada.']]),'O vetor original é (0,1). A sua segunda coordenada é 1, mas a segunda coordenada do resultado é 0.','Logo (0,0) ≠ (0,1), apesar de todos os valores escolhidos serem permitidos.'],'A8 falha.')
  ]);

  const pairC=indexed({setup:'Os vetores u = (u₁,u₂), v = (v₁,v₂) e w = (w₁,w₂) têm coordenadas complexas. Fixamos k ∈ {1,2}. A soma # é a soma usual em cada coordenada.',at:a=>`(${a})<sub>k</sub>`,u:'uₖ',v:'vₖ',w:'wₖ',zero:'(0,0)',zeroMember:'As duas coordenadas são complexas, logo o par pertence a ℂ².',inverse:'(−u₁,−u₂)',inverseMember:'O oposto de cada coordenada complexa é complexo, portanto o par pertence a ℂ².',finish:'A igualdade vale para k = 1 e para k = 2. Como as duas coordenadas coincidem, os pares complexos são iguais.'}).map(html=>html.replace(/números reais/g,'números complexos').replace(/número real/g,'número complexo').replace(/adição real/g,'adição complexa'));
  proofs.a5=pairC.slice(0,4).concat([
    proof('Vamos comparar os dois lados para um escalar complexo e dois vetores permitidos.',[
      'Escolhemos α = i, u = (1,0) e v = (0,1). O escalar i está em ℂ e os dois vetores estão em ℂ². O conjugado de i = 0 + 1i é −i.',
      'Calculamos a soma antes da multiplicação:'+calc([['u # v = (1 + 0, 0 + 1) = (1,1)','A soma # é usual.'],['i ⊙ (u # v) = (−i × 1, −i × 1) = (−i,−i)','A segunda coordenada de (1,1) é diferente de zero: usamos o conjugado do escalar.']]),
      'Calculamos agora os dois produtos antes de somar:'+calc([['i ⊙ u = i ⊙ (1,0) = (i × 1,i × 0) = (i,0)','A segunda coordenada de u é zero: usamos i, sem conjugar.'],['i ⊙ v = i ⊙ (0,1) = (−i × 0,−i × 1) = (0,−i)','A segunda coordenada de v é não nula: usamos −i.'],['(i ⊙ u) # (i ⊙ v) = (i,0) # (0,−i) = (i,−i)','Somamos as duas coordenadas.']]),
      'As primeiras coordenadas são −i e i. São diferentes: as partes imaginárias são −1 e 1.'
    ],fail),
    proof('Fixamos α, β ∈ ℂ e u = (z,w) ∈ ℂ². Mantemos o mesmo vetor u nos dois produtos do lado direito.',[
      'Primeiro verificamos a identidade dos conjugados. Escrevemos α = a + bi e β = c + di, com a,b,c,d reais:'+calc([['conj(α + β) = conj((a + c) + (b + d)i)','Somamos partes reais e imaginárias.'],['= (a + c) − (b + d)i','Definição de conjugado.'],['= (a − bi) + (c − di) = ᾱ + β̄','Reagrupamos a soma usual.']]),
      'Se w = 0, a regra é a multiplicação usual:'+calc([['(α + β) ⊙ (z,0) = ((α + β)z,0)','Usamos o ramo w = 0.'],['= (αz + βz,0)','Distributividade nos complexos.'],['= (αz,0) # (βz,0) = (α ⊙ u) # (β ⊙ u)','Cada produto separado usa o mesmo ramo.']]),
      'Se w ≠ 0, todos os produtos usam o ramo com conjugado:'+calc([['(α + β) ⊙ (z,w) = (conj(α + β)z, conj(α + β)w)','Definição neste ramo.'],['= ((ᾱ + β̄)z, (ᾱ + β̄)w)','Identidade dos conjugados já calculada.'],['= (ᾱz + β̄z, ᾱw + β̄w)','Distributividade complexa em cada coordenada.'],['= (ᾱz,ᾱw) # (β̄z,β̄w)','Definição da soma usual.'],['= (α ⊙ u) # (β ⊙ u)','Definição de cada produto, pois o vetor de entrada continua a ser u.']])
    ],'Os casos w = 0 e w ≠ 0 cobrem todos os vetores. Logo A6 é satisfeita, mesmo se α + β = 0.'),
    proof('Fixamos α, β ∈ ℂ e u = (z,w). É necessário verificar que ramo usa o produto exterior.',[
      'Vamos justificar a identidade conj(αβ) = ᾱβ̄. Se α = a + bi e β = c + di, então:'+calc([['αβ = ac + adi + bci + bd i² = (ac − bd) + (ad + bc)i','Distribuímos e usamos i² = −1.'],['conj(αβ) = (ac − bd) − (ad + bc)i','Definição de conjugado.'],['ᾱβ̄ = (a − bi)(c − di) = ac − adi − bci + bd i²','Expandimos o produto dos conjugados.'],['= (ac − bd) − (ad + bc)i = conj(αβ)','Os resultados são iguais.']]),
      'Caso w = 0: β ⊙ (z,0) = (βz,0), cuja segunda coordenada continua a ser zero. Então:'+calc([['α ⊙ (β ⊙ u) = α ⊙ (βz,0) = (αβz,0)','Os dois produtos usam o ramo sem conjugado.'],['(αβ) ⊙ u = (αβ) ⊙ (z,0) = (αβz,0)','O produto direto usa o mesmo ramo.']]),
      'Caso w ≠ 0 e β = 0: o conjugado de 0 é 0, logo β ⊙ u = (0,0). Depois α ⊙ (0,0) = (α × 0,α × 0) = (0,0), pelo ramo de segunda coordenada zero. Do outro lado, αβ = 0, e (αβ) ⊙ u = (0,0).',
      'Caso w ≠ 0 e β ≠ 0: o conjugado β̄ também é não nulo (se c − di = 0, teríamos c = d = 0 e β = 0). O produto β̄w é não nulo, pois um produto de dois complexos não nulos não é zero. Por isso o vetor β ⊙ u = (β̄z,β̄w) continua no ramo com conjugado. Assim:'+calc([['α ⊙ (β ⊙ u) = (ᾱ(β̄z),ᾱ(β̄w))','O produto exterior também conjuga o escalar.'],['= ((ᾱβ̄)z,(ᾱβ̄)w)','Associatividade da multiplicação complexa.'],['= (conj(αβ)z,conj(αβ)w)','Identidade demonstrada na primeira etapa.'],['= (αβ) ⊙ u','u tem segunda coordenada não nula.']])
    ],'Verificámos todas as possibilidades para w e β. Em cada uma, os dois lados de A7 coincidem.'),
    proof('Fixamos u = (z,w) ∈ ℂ². O escalar 1 é o complexo 1 + 0i.', ['O conjugado de 1 é 1 − 0i = 1.', 'Se w = 0, usamos o primeiro ramo:'+calc([['1 ⊙ (z,0) = (1z,1 × 0) = (z,0)','Identidade da multiplicação complexa.']]),'Se w ≠ 0, usamos o segundo ramo:'+calc([['1 ⊙ (z,w) = (conj(1)z,conj(1)w) = (1z,1w) = (z,w)','O conjugado de 1 continua a ser 1.']])],'Em ambos os casos, o vetor é conservado. A8 é satisfeita.')
  ]);
  proofs.a7=C.slice(0,4).concat([
    proof('Fixamos α, u, v ∈ ℂ. A regra usa o número real Re(α), que também pode ser visto como um complexo.', ['A soma # é a usual dos complexos.',calc([['α ⊙ (u # v) = Re(α)(u + v)','Substituímos as operações pelas definições.'],['= Re(α)u + Re(α)v','Distributividade da multiplicação complexa.'],['= (α ⊙ u) + (α ⊙ v)','Definição dos dois produtos escalares.'],['= (α ⊙ u) # (α ⊙ v)','Definição da soma #.']]),'O cálculo não exige que α seja real: só o seu fator Re(α) é real.'],all),
    proof('Fixamos α, β, u ∈ ℂ e escrevemos α = a + bi, β = c + di, com coeficientes reais.', [calc([['α + β = (a + c) + (b + d)i','Soma usual de complexos.'],['Re(α + β) = a + c = Re(α) + Re(β)','Definição da parte real.']]),calc([['(α + β) ⊙ u = Re(α + β)u','Definição da operação.'],['= (Re(α) + Re(β))u','Usamos a identidade calculada acima.'],['= Re(α)u + Re(β)u','Distributividade da multiplicação usual.'],['= (α ⊙ u) # (β ⊙ u)','Definições da operação escalar e da soma.']]),'A igualdade vale para qualquer escolha das quatro partes reais e imaginárias.'],all),
    proof('Escolhemos os escalares α = β = i e o vetor u = 1. Todos pertencem a ℂ.', [calc([['αβ = i × i = i² = −1','Produto dos dois escalares.'],['(αβ) ⊙ u = (−1) ⊙ 1 = Re(−1) × 1 = −1','A parte real de −1 é −1.']]),calc([['β ⊙ u = i ⊙ 1 = Re(i) × 1 = 0','A parte real de i = 0 + 1i é 0.'],['α ⊙ (β ⊙ u) = i ⊙ 0 = Re(i) × 0 = 0','Aplicamos a operação ao resultado interior.']]),'Obtivemos −1 para um lado e 0 para o outro. São números complexos diferentes.'],fail),
    proof('Fixamos u ∈ ℂ e tomamos o escalar 1 = 1 + 0i.', ['Pela definição da parte real, Re(1) = 1.',calc([['1 ⊙ u = Re(1)u','Definição de ⊙.'],['= 1u','Substituímos Re(1) por 1.'],['= u','Identidade da multiplicação usual dos complexos.']]),'O cálculo vale para qualquer complexo u.'],'A8 é satisfeita.')
  ]);

  const closureProofs={};
  closureProofs.r2=proof('As operações têm de devolver elementos de E para todos os dados permitidos.', ['O par (0,0) tem coordenadas reais, portanto E não é vazio.', 'Se u = (x,y) e v = (s,t) têm coordenadas reais, então x+s e y+t são reais. Por isso u # v = (x+s,y+t) pertence a ℝ².', 'Se α é real e u = (x,y) está em ℝ², então αx e αy são reais. Logo α ⊙ u = (αx,αy) pertence a ℝ², mesmo para α = 0 ou α < 0.'],'As duas operações são fechadas em E.');
  closureProofs.matrices=proof('Uma matriz pertence a E se tem duas linhas, duas colunas e todas as entradas reais.', ['A matriz nula de 2 × 2 tem essas propriedades, logo E não é vazio.', 'Para A,B ∈ E, cada entrada aᵢⱼ + bᵢⱼ é soma de dois reais e é real. Não se acrescentam nem se retiram linhas ou colunas. Assim A # B ∈ E.', 'Para α ∈ ℝ e A ∈ E, cada entrada αaᵢⱼ é um produto real. A matriz obtida continua a ter tamanho 2 × 2. Logo α ⊙ A ∈ E.'],'Os dois fechos são satisfeitos.');
  closureProofs.polynomials=proof('Aqui são permitidos todos os polinómios a + bx + cx², incluindo aqueles com c = 0.', ['O polinómio nulo tem a=b=c=0, portanto E não é vazio.', 'Se p(x)=a+bx+cx² e q(x)=d+ex+fx², então p # q = (a+d)+(b+e)x+(c+f)x². Os três novos coeficientes são reais e não há termos de grau maior que 2. Portanto p # q ∈ E.', 'Para α ∈ ℝ, temos α ⊙ p = (αa)+(αb)x+(αc)x². Os três coeficientes são reais. Se α=0, obtemos o polinómio nulo, que também está em E.'],'As operações são fechadas em E.');
  closureProofs.functions=proof('Para pertencer a E, basta definir um valor real em cada ponto real.', ['A função f(t)=0 para todos os t é um exemplo, logo E não é vazio.', 'Se f,g:ℝ→ℝ, então para cada t os números f(t) e g(t) são reais. A soma f(t)+g(t) existe e é real. A regra (f # g)(t)=f(t)+g(t) define, por isso, uma função de ℝ em ℝ.', 'Se α∈ℝ, então αf(t) é real para todo o t. Assim a regra (α ⊙ f)(t)=αf(t) também define uma função de ℝ em ℝ.'],'As duas operações têm valores em E. Não é exigida continuidade, derivabilidade ou qualquer outra condição.');
  closureProofs.sequences=proof('Uma sucessão de E tem um termo real para cada índice natural n ≥ 1.', ['A sucessão (0,0,0,…) pertence a E, logo o conjunto não é vazio.', 'Se u=(uₙ) e v=(vₙ) estão em E, a expressão uₙ+vₙ é um real para cada n. A regra que associa esse número a n define outra sucessão real, u # v.', 'Para qualquer α∈ℝ, cada termo αuₙ é real; logo α ⊙ u=(αuₙ) também pertence a E. Nenhuma destas definições exige somar infinitos termos.'],'As operações são fechadas, sem qualquer hipótese de convergência.');
  closureProofs['complex-real']=proof('Os vetores são complexos e os escalares são reais.', ['O complexo 0+0i pertence a E, logo E não é vazio.', 'Se u=x+iy e v=s+it, então u # v=(x+s)+i(y+t). As partes x+s e y+t são reais, logo a soma é um complexo.', 'Se α∈ℝ, então α ⊙ u=αx+iαy. As duas partes αx e αy são reais, logo o resultado pertence a ℂ.'],'As duas operações são fechadas sobre o conjunto de complexos com estes escalares reais.');
  closureProofs.waves=proof('Um elemento de E tem a forma a sen t + b cos t, com a,b reais.', ['A função nula é 0 sen t + 0 cos t, por isso E não é vazio.',calc([['(a sen t + b cos t) + (c sen t + d cos t)','Soma de dois elementos quaisquer.'],['= (a+c) sen t + (b+d) cos t','Reagrupamos os termos com seno e os termos com cosseno.']]),'Como a+c e b+d são reais, o resultado está em E.',calc([['α(a sen t + b cos t) = (αa) sen t + (αb) cos t','Distributividade real.']]),'Os coeficientes αa e αb são reais, portanto qualquer produto por um escalar também está em E.'],'Os dois fechos são satisfeitos.');
  closureProofs['plane-equation']=proof('É preciso que os resultados satisfaçam a equação x−y+z=0.', ['O vetor (0,0,0) satisfaz 0−0+0=0, por isso E não é vazio.', 'Se u=(x,y,z) e v=(s,t,r) estão em E, sabemos x−y+z=0 e s−t+r=0. Para a soma:'+calc([['(x+s) − (y+t) + (z+r) = (x−y+z) + (s−t+r)','Distribuímos o sinal menos e reagrupamos somas reais.'],['= 0 + 0 = 0','Usamos as duas hipóteses de pertença a E.']]),'Logo u # v está no plano.', 'Para α∈ℝ:'+calc([['αx − αy + αz = α(x−y+z)','Distributividade real.'],['= α × 0 = 0','Usamos a hipótese de que u pertence ao plano.']]),'Assim α ⊙ u também pertence a E.'],'O plano é fechado para ambas as operações.');
  closureProofs.positive=proof('O conjunto contém apenas números estritamente positivos, mas todos os reais são escalares.', ['O número 1 é positivo, portanto E não é vazio.', 'Se u>0 e v>0, então uv>0. Como u # v=uv, a soma abstrata permanece em E.', 'Se u>0 e α∈ℝ, ln u existe e α ln u é real. A exponencial de qualquer real é positiva. Logo uᵅ=exp(α ln u)>0 e α ⊙ u∈E. Isso inclui α=0 e escalares negativos.'],'As operações definidas são fechadas em E.');
  closureProofs.shifted=proof('Precisamos apenas de verificar que cada resultado é real.', ['0 pertence a ℝ, portanto o conjunto não é vazio (ser um elemento do conjunto não significa ser o neutro).', 'Se u,v∈ℝ, os números u+v e (u+v)−3 são reais. Logo u # v=u+v−3 pertence a E.', 'Se α,u∈ℝ, então u−3 é real, α(u−3) é real e 3+α(u−3) é real. Por isso α ⊙ u pertence a E.'],'As duas operações são definidas para todos os dados permitidos e são fechadas em E.');
  closureProofs.mismatch=proof('O conjunto é ℝ.', ['0 é um real, logo E não é vazio.', 'Se u,v∈ℝ, então u+v+1 é real, logo u # v∈E.', 'Se α,u∈ℝ, o produto usual αu é real, logo α ⊙ u∈E.'],'Ambos os fechos são satisfeitos. Isso ainda não prova os oito axiomas.');
  closureProofs.a1=proof('A escolha entre dois ramos deve dar sempre um par real.', ['O par (0,0) pertence a E, portanto o conjunto não é vazio.', 'Para u,v∈ℝ², os produtos reais u₁v₂ e u₂v₁ são iguais ou diferentes. Se forem iguais, u # v=(u₁+v₁,u₂+v₂) tem duas coordenadas reais. Se forem diferentes, u # v=(2(u₁+v₁),2(u₂+v₂)) também tem duas coordenadas reais. Exatamente um destes casos ocorre, por isso a regra dá um único resultado em E para quaisquer u e v.', 'Para qualquer α∈ℝ e u=(u₁,u₂), o produto α ⊙ u=(αu₁,αu₂) tem as duas coordenadas reais.'],'As duas operações são fechadas em ℝ².');
  for(const id of ['a2','a3'])closureProofs[id]=proof('A soma escolhe o maior argumento; a operação escalar devolve o próprio vetor.', ['0 pertence ao conjunto apresentado, logo E não é vazio.', 'Se u,v∈E, então máx(u,v) é igual a u ou a v (se são iguais, é igual a ambos). Portanto o resultado continua a pertencer a E.', 'Para qualquer real α e qualquer u∈E, a definição dá α ⊙ u=u. Como u já estava no conjunto, o resultado também está.'],'Os dois fechos são satisfeitos, incluindo para escalares nulos e negativos.');
  closureProofs.a5=proof('Os vetores e os escalares são complexos.', ['O par (0,0) pertence a ℂ², logo E não é vazio.', 'Somar dois pares de complexos produz um complexo em cada coordenada, logo a soma # está em ℂ².', 'Para α∈ℂ, tanto α como ᾱ são complexos. Se a segunda coordenada do vetor é zero, multiplicamos as duas coordenadas por α; caso contrário, por ᾱ. Em ambos os ramos, cada produto é complexo.'],'Cada par permitido de argumentos produz um resultado em E.');
  for(const id of ['a6','absolute'])closureProofs[id]=proof('O conjunto de vetores é ℝ e todos os escalares são reais.', ['0∈ℝ, portanto E não é vazio.', 'A soma u # v=u+v de quaisquer reais é real.', `Para α,u∈ℝ, o fator ${id==='a6'?'α²':'|α|'} é real. O seu produto por u também é real, logo α ⊙ u∈E.`],'Ambas as operações são fechadas.');
  closureProofs.a7=proof('O corpo de escalares e o conjunto de vetores são ambos ℂ.', ['O complexo 0 está em E, logo o conjunto é não vazio.', 'A soma de dois complexos é complexa, logo u # v∈E.', 'Se α=a+bi é complexo, Re(α)=a é real e também complexo. Se u=x+iy, então Re(α)u=ax+iay é um complexo. Assim α ⊙ u∈E.'],'As operações são fechadas para todos os escalares complexos.');
  closureProofs.a8=proof('O conjunto de vetores é ℝ.', ['0 é real, portanto E não é vazio.', 'A soma usual de dois reais é real, logo # é fechada.', 'Todo o produto α ⊙ u é, por definição, 0. Como 0∈ℝ, a operação escalar também é fechada.'],'Os dois fechos são satisfeitos.');
  closureProofs.projection=proof('O conjunto de vetores é ℝ².', ['(0,0)∈ℝ², portanto E não é vazio.', 'A soma usual de dois pares reais é um par real.', 'Se α,x,y são reais, αx é real e 0 também. Assim (αx,0)∈ℝ² para qualquer escalar α e vetor (x,y).'],'As operações não saem de E. Apagar uma coordenada não impede, por si só, o fecho.');

  proofs.halfplane=[
    proof('Precisamos de mostrar que a soma fica no semiplano para quaisquer dois vetores dele.', ['Escolhemos u=(x,y) e v=(s,t) em E. Pela definição de E, y≥0 e t≥0; x e s podem ser quaisquer reais.',calc([['u # v = (x+s,y+t)','Definição da soma usual.'],['y+t ≥ 0+0 = 0','A soma de dois números não negativos é não negativa.']]),'A segunda coordenada da soma satisfaz a condição de E; as duas coordenadas são reais. Portanto u # v∈E.'],'Como u e v eram quaisquer, o fecho para a adição é satisfeito.'),
    proof('Basta um escalar permitido e um vetor de E cujo produto fique fora do conjunto.', ['Escolhemos u=(0,1). A segunda coordenada é 1≥0, logo u∈E. Escolhemos α=−1, que é um escalar permitido porque o corpo é ℝ.',calc([['α ⊙ u = (−1)(0,1)','Usamos a operação escalar usual.'],['= ((−1)×0,(−1)×1) = (0,−1)','Multiplicamos cada coordenada.']]),'A segunda coordenada é −1<0. Por isso (0,−1) não pertence a E.'],'O fecho para todos os escalares reais falha. Não basta verificar apenas escalares positivos.')
  ];
  proofs.circle=[
    proof('A condição para pertencer a E é x²+y²=1.', ['Escolhemos u=v=(1,0). Para cada um, 1²+0²=1, logo os dois vetores estão em E.',calc([['u # v = (1,0)+(1,0) = (2,0)','Soma coordenada a coordenada.'],['2²+0² = 4+0 = 4 ≠ 1','Testamos a equação de pertença para o resultado.']]),'Embora ambos os argumentos pertençam à circunferência, o resultado não pertence.'],'O fecho para a adição falha.'),
    proof('Para a multiplicação escalar, todos os reais têm de ser permitidos, incluindo 0.', ['Escolhemos u=(1,0), que pertence à circunferência porque 1²+0²=1. Escolhemos α=0∈ℝ.',calc([['0 ⊙ (1,0) = (0×1,0×0) = (0,0)','Definição do produto escalar usual.'],['0²+0² = 0 ≠ 1','O resultado não satisfaz a equação da circunferência.']]),'O vetor de entrada e o escalar são permitidos, mas o vetor de saída não está em E.'],'O fecho para os escalares falha.')
  ];
  proofs.integers=[
    proof('Os vetores de E têm duas coordenadas inteiras.', ['Escolhemos u=(m,n) e v=(p,q) em ℤ². Assim m,n,p,q são inteiros.',calc([['u # v = (m+p,n+q)','Soma usual dos pares.']]),'A soma de dois inteiros é inteira. Logo m+p∈ℤ e n+q∈ℤ, pelo que o par resultado pertence a ℤ².'],'O argumento vale para quaisquer u,v∈E, portanto a adição é fechada.'),
    proof('O conjunto dos vetores é ℤ², mas o corpo de escalares continua a ser ℝ.', ['Escolhemos u=(1,0). As suas coordenadas são inteiras, logo u∈E. Escolhemos α=1/2, que é um real e é um escalar permitido.',calc([['α ⊙ u = (1/2)(1,0)','Substituímos na operação usual.'],['= ((1/2)×1,(1/2)×0) = (1/2,0)','Multiplicamos as coordenadas.']]),'O número 1/2 não é inteiro. Por isso a primeira coordenada do resultado não é permitida e (1/2,0)∉ℤ².'],'O fecho para todos os escalares reais falha.')
  ];
  proofs['exact-quadratics']=[
    proof('Aqui o coeficiente de x² tem de ser diferente de zero.', ['Escolhemos p(x)=x² e q(x)=−x². Os seus coeficientes quadráticos são 1 e −1, ambos não nulos; por isso p,q∈E.',calc([['(p # q)(x) = p(x)+q(x)','Definição da soma.'],['= x²+(−x²) = (1−1)x² = 0','Os termos de grau 2 anulam-se.']]),'O resultado tem coeficiente de x² igual a 0, que não é permitido em E. É o polinómio nulo, não um polinómio de grau exato 2.'],'A soma de dois elementos de E pode sair de E. O fecho para a adição falha.'),
    proof('Escolhemos um polinómio permitido e multiplicamo-lo pelo escalar 0.', ['Tomamos p(x)=x²∈E, pois o seu coeficiente quadrático é 1≠0. O escalar α=0 é permitido, porque o corpo é ℝ.',calc([['(0 ⊙ p)(x) = 0p(x)','Definição do produto escalar.'],['= 0x² = 0','O resultado é o polinómio nulo.']]),'O coeficiente de x² do resultado é 0. Isso viola a condição c≠0 que define E.'],'O produto de um escalar permitido por um vetor de E pode sair de E. O fecho para os escalares falha.')
  ];

  const dependence=proof('Suponhamos que A1, A2, A3, A5, A6 e A8 são satisfeitas. Não vamos usar A4 nem A7. Fixamos u,v∈E e mostraremos u # v = v # u.',[
    'Desenvolvemos T = (1+1) ⊙ (u # v), primeiro usando a soma dos escalares:'+calc([['T = (1 ⊙ (u # v)) # (1 ⊙ (u # v))','A6, com os dois escalares iguais a 1.'],['= (u # v) # (u # v)','A8 em cada uma das duas parcelas.']]),
    'Desenvolvemos o mesmo T, agora começando pela soma dos vetores:'+calc([['T = ((1+1) ⊙ u) # ((1+1) ⊙ v)','A5.'],['= ((1 ⊙ u) # (1 ⊙ u)) # ((1 ⊙ v) # (1 ⊙ v))','A6 aplicada separadamente a u e a v.'],['= (u # u) # (v # v)','A8 nas quatro ocorrências.']]),
    'Assim, (u # v) # (u # v) = (u # u) # (v # v). Vamos apenas mudar parênteses, sem trocar a ordem de quaisquer elementos:'+calc([['(u # v) # (u # v) = ((u # v) # u) # v','A1: a # (b # c) = (a # b) # c.'],['= (u # (v # u)) # v','A1 na soma dos três primeiros elementos.'],['= u # ((v # u) # v)','A1 de novo.'],['(u # u) # (v # v) = u # (u # (v # v))','A1.'],['= u # ((u # v) # v)','A1 dentro dos parênteses.']]),
    'Definimos X = (v # u) # v e Y = (u # v) # v. A igualdade obtida é u # X = u # Y. Por A3 existe u′ com u′ # u = 0<sub>E</sub>. Somamos esse mesmo u′ à esquerda dos dois membros:'+calc([['u′ # (u # X) = u′ # (u # Y)','Aplicamos a mesma operação a dois elementos iguais.'],['(u′ # u) # X = (u′ # u) # Y','A1 dos dois lados.'],['0<sub>E</sub> # X = 0<sub>E</sub> # Y','A3, pela escolha de u′.'],['X = Y','A2: o neutro à esquerda não altera o elemento.']]),
    'Substituímos X e Y: (v # u) # v = (u # v) # v. Por A3 existe v′ com v # v′ = 0<sub>E</sub>. Somamos v′ à direita dos dois membros:'+calc([['((v # u) # v) # v′ = ((u # v) # v) # v′','Aplicamos a mesma operação à direita.'],['(v # u) # (v # v′) = (u # v) # (v # v′)','A1 dos dois lados.'],['(v # u) # 0<sub>E</sub> = (u # v) # 0<sub>E</sub>','A3, pela escolha de v′.'],['v # u = u # v','A2: o neutro à direita não altera o elemento.']])
  ],'Como u e v eram arbitrários, acabámos de provar A4 a partir dos outros axiomas indicados. Portanto não pode existir uma estrutura que satisfaça os outros sete e falhe apenas A4.');
  const identityDependence=proof('O enunciado de A3 nas notas usa o elemento neutro 0<sub>E</sub> introduzido em A2.', ['A2 exige a existência de um elemento 0<sub>E</sub> em E que deixe todo o u inalterado dos dois lados.', 'A3 exige, para cada u, um u′ cuja soma com u dê esse elemento neutro. Não se trata de dar à soma o valor de um elemento arbitrariamente escolhido.', 'Se não existir um neutro, a exigência de A3 no sentido das notas também não é satisfeita. Por isso, neste percurso, o caso sem neutro é explicitamente identificado como falhando A2 e A3.'],'Não afirmamos que isto se aplique a qualquer outra formalização de «zero». É uma consequência da formulação usada nesta aula.');

  function attach(example) {
    if(!proofs[example.id]) throw new Error('Missing detailed proof for '+example.id);
    example.explanations=proofs[example.id];
    if(closureProofs[example.id])example.closureProof=closureProofs[example.id];
    if(example.id==='a2')example.extra=identityDependence;
    const overlines=html=>html.replace(/([αβ1])\u0304/g,'<span class="overline">$1</span>').replace(/conj\((α \+ β|αβ|1)\)/g,'<span class="overline">$1</span>').replace('conj((a + c) + (b + d)i)','<span class="overline">(a + c) + (b + d)i</span>');
    example.explanations=example.explanations.map(overlines);
    for(const key of Object.keys(example))if(typeof example[key]==='string')example[key]=overlines(example[key]);
    return example;
  }
  return {attach,dependence,identityDependence};
})();
if (typeof module !== 'undefined' && module.exports) module.exports=VectorProofs;
