# Site settings
title: Homepage
description: Alexander Taveira Blomenhofer
baseurl: "" # Leave this empty for GitHub Pages, set to "/your-repo-name" if using a custom domain

# Theme settings (if using the Architect theme)
remote_theme: pages-themes/architect@v0.2.0

gem "github-pages", group: :jekyll_plugins

# Build settings
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-github-metadata

# Exclude files and directories from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - _site
  - .sass-cache
  - .jekyll-cache

# Markdown settings
markdown: kramdown
highlighter: rouge

# URL settings
url: "https://a44l.github.io" # Replace with your GitHub Pages URL

# Navigation settings
# Example navigation items, you can add more as needed
nav:
  - title: Home
    url: /
  - title: cv
    url: /cv/
  - title: Publications
    url: /publications/
  - title: "Talks and Posters"
    url: /talks/
  - title: Contact
    url: /contact/
  
# GitHub
# repository: "a44l/a44l.github.io"
# github: [metadata]

# Social media settings
# Replace with your social media profiles
social:
  - title: GitHub
    url: https://github.com/a44l

# Build options
# Set this to true when using GitHub Pages
# Set this to false if you are building the site locally and want to preview drafts and unpublished posts
published: false

