window.PRACTICE_MESSAGES = {
  chooseOne: "Escolha uma opção",
  chooseInstruction: "Selecione a resposta mais adequada.",
  intruder: "Encontre a intrusa",
  intruderInstruction: "Selecione a única opção que não satisfaz a condição indicada.",
  proof: "Ideia da demonstração",
  proofInstruction: "Escolha o passo que completa o argumento.",
  numeric: "Cálculo rápido",
  numericInstruction: "Introduza uma resposta numérica. São aceites vírgula ou ponto decimal, frações e percentagens quando adequado.",
  start: "Iniciar sessão — {bank}",
  review: "Rever os slides das aulas",
  answerPlaceholder: "A sua resposta",
  answerLabel: "A sua resposta numérica",
  number: "número",
  counter: "Exercício {current} de {total}",
  difficulty_intro: "introdução",
  difficulty_core: "consolidação",
  difficulty_challenge: "desafio",
  correct: "Correto — continue!",
  incorrect: "Ainda não. Resposta: {answer}",
  reviewSlide: "Rever slide {slide}",
  results: "Ver resultados",
  continue: "Continuar",
  perfect: "Sessão perfeita. Relacionou todas as ideias deste conjunto.",
  strong: "Muito bem. Os conhecimentos estão a consolidar-se.",
  progress: "Bom progresso. Releia as explicações e experimente um novo conjunto.",
  encouragement: "É assim que se aprende: pequenas tentativas, explicações imediatas e mais uma sessão.",
  loadError: "Não foi possível carregar os exercícios. Atualize a página e tente novamente.",
};
